# docker-compose.yml
version: "3.3"
services:
   openldap:
      build:
         context: ./OpenLDAP/
         dockerfile: Dockerfile
      hostname: openldap
      environment:
         - LDAP_ORGANISATION="My Company" 
         - LDAP_DOMAIN="my-company.com"
         - LDAP_ADMIN_PASSWORD="JonSn0w"
   phpldapadmin:
      build: 
         context: ./phpLDAPAdmin/
         dockerfile: Dockerfile
      hostname: phpldapadmin
      ports:
         - 8080:8080
   subversionedge:
      build:
         context: ./SubversionEdge/
         dockerfile: Dockerfile
      hostname: subversionedge
#      env_file: ./subversionedge/.env
      volumes:
         - ./db-data:/app/instance
      ports:
         - 3343:3343
         - 4434:4434
         - 18080:18080
   bugzilla:
      build:
         context: ./Bugzilla/
         dockerfile: Dockerfile
      hostname: bugzilla
         
