version: "3.1"

services:

# SUBVERSION SERVICE: Subversion EDGE 
  subversion-service:
    build: 
       dockerfile: Dockerfile
       context: ./SubversionEdge/
    container_name: subversion-service
    hostname: subversion-host
    restart: always
    links: 
      - "ldap-service:ldap-host"
    volumes:
      - "${BASEPATH}/svndata:/opt/csvn/data"
    ports:
      - 3343:3343
      - 4434:4434
      - 18080:18080
    networks:
      - backend
      - frontend

# LDAPADMIN SERVICE - php LDAP Admin v0.9.0
  ldapadmin-service:
     image: osixia/phpldapadmin:0.9.0 
     container_name: ldapadmin-service
     hostname: ldapadmin-host
     restart: always
     links:
       - "ldap-service:ldap-host"
     environment:
       - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
       - PHPLDAPADMIN_HTTPS=false
     ports:
       - 4040:80
#       - 443:443
     networks:
       - frontend
       - backend

# LDAPPASSWD SERVICE - LDAP Self Service Password   
  ldappasswd-service:
    build:
      context: ./SelfServicePassword/
      dockerfile: Dockerfile
    container_name: ldappasswd-service
    hostname: ldappasswd-host
    restart: always
    links:
      - "ldap-service:ldap-host"
    volumes:
      - "${BASEPATH}/ldappasswd/conf:/var/www/conf"
      - "${BASEPATH}/ldappasswd/images:/var/www/html/images"
    ports:
      - 9090:80
    networks:
      - frontend
      - backend

# LDAP SERVICE - Open LDAP v 1.4.0 [Backend]       
  ldap-service:
    image: osixia/openldap:1.4.0
    container_name: ldap-service
    hostname: ldap-host
    restart: always
    volumes:
      - "${BASEPATH}/ldap-db:/var/lib/ldap"
      - "${BASEPATH}/ldap-conf:/etc/ldap/slapd.d"
    environment:
      - LDAP_ORGANISATION=Example
      - LDAP_DOMAIN=example.org 
      - LDAP_ADMIN_PASSWORD=password
    networks:
      - backend

# BUGZILLA SERVICE - Bugzilla
  bugzilla-service:
     image: herzcthu/bugzilla:latest
     container_name: bugzilla-service
     hostname: bugzilla-host
     volumes:
       - "${BASEPATH}/bugzilla/localconfig:/usr/local/apache2/htdocs/localconfig"
     ports:
       - 8080:80
#       - 5900:5900
     links:
       - "mysql-service:mysql"
       - "ldap-service:ldap-host"
     restart: always
     networks:
       - frontend
       - backend

# MYSQL SERVICE - MySQL v 5.7 [Backend]         
  mysql-service:
     image: mysql:5.7
     container_name: mysql-service
     hostname: mysql-host
     command: --default-authentication-plugin=mysql_native_password
     volumes:
       - "${BASEPATH}/mysql:/var/lib/mysql"
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=bugs
       - MYSQL_USER=bugs
       - MYSQL_PASSWORD=bugs
     restart: always
     networks:
       - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER:-bridge}
    ipam:
      driver: default
      config:
      - subnet:  ${FRONTEND_SUBNET:-192.168.168.0/25}

  backend:
    driver: ${NETWORKS_DRIVER:-bridge}
    ipam:
      driver: default
      config:
      - subnet: ${BACKEND_SUBNET:-192.168.168.128/25}
